### ISSUE TITLE
Support shells other than bash

### ISSUE THREAD

**Issue by ryanrousseau** [CircleCI-Public/rememborb#2]
Hello,

I'm trying to use this orb with jobs that run on different containers. One of the containers does not have bash installed. In this case, the value isn't recalled.

Here's an config that shows the case in action.

`version: 2.1

orbs:
  mem: circleci/rememborb@0.0.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1.607-stretch
    steps:
      - run: echo $0
      - mem/remember:
          env_var: VERSION
          value: "1.0.$CIRCLE_BUILD_NUM"
  package:
    docker:
      - image: octopusdeploy/octo:latest
    steps:
      - run: echo $0
      - mem/recall:
          env_var: VERSION
      - run: echo Recalled VERSION = ${VERSION}

workflows:
  version: 2
  build:
    jobs:
      - build
      - package:
          requires:
            - build
`

The workflow will succeed, but if you expand the logs for the line that echos the recalled value, you'll see that it is blank.

**Comment by lokst** [comment]
Thanks for filing this @ryanrousseau ! Our recommendation is to add a step to install `bash` in your container as we don't currently have plans to add support for alternative shells.
